/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package fr.solutec.ihm;

/**
 *
 * @author esic
 */
public class FnConnected extends javax.swing.JFrame {

    /**
     * Creates new form FnConnected
     */
    public FnConnected() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        BtHistoHebdo = new javax.swing.JButton();
        BtHistoQuot = new javax.swing.JButton();
        BtAperObj = new javax.swing.JButton();
        BtCreaObj = new javax.swing.JButton();
        BtProfil = new javax.swing.JButton();
        BtDeconnexion = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Bienvenue à toi ! ");

        jLabel2.setText("Dernière co le ...");

        BtHistoHebdo.setText("Historique Hebdomadaire");
        BtHistoHebdo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtHistoHebdoActionPerformed(evt);
            }
        });

        BtHistoQuot.setText("Historique Quotidien");
        BtHistoQuot.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtHistoQuotActionPerformed(evt);
            }
        });

        BtAperObj.setText("Aperçu objectif en cours");
        BtAperObj.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtAperObjActionPerformed(evt);
            }
        });

        BtCreaObj.setText("Création d'un objectif");
        BtCreaObj.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtCreaObjActionPerformed(evt);
            }
        });

        BtProfil.setText("Accès Profil");
        BtProfil.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtProfilActionPerformed(evt);
            }
        });

        BtDeconnexion.setText("Déconnexion");
        BtDeconnexion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtDeconnexionActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(BtProfil)
                .addGap(49, 49, 49))
            .addGroup(layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(BtDeconnexion)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(BtHistoHebdo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(BtCreaObj, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(BtAperObj, javax.swing.GroupLayout.DEFAULT_SIZE, 174, Short.MAX_VALUE)
                            .addComponent(BtHistoQuot, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(0, 7, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(8, 8, 8)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(BtProfil))
                .addGap(58, 58, 58)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(BtHistoHebdo)
                    .addComponent(BtHistoQuot))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(BtAperObj)
                    .addComponent(BtCreaObj))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 83, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(BtDeconnexion)
                        .addGap(17, 17, 17))))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BtHistoHebdoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtHistoHebdoActionPerformed
     FnHistoHebdo FnHistHebd = new FnHistoHebdo();
     FnHistHebd.setVisible(true);
     this.setVisible(false);
    }//GEN-LAST:event_BtHistoHebdoActionPerformed

    private void BtDeconnexionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtDeconnexionActionPerformed
    FnHome FnHo = new FnHome();
    FnHo.setVisible(true);
    this.setVisible(false);
    }//GEN-LAST:event_BtDeconnexionActionPerformed

    private void BtProfilActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtProfilActionPerformed
     FnProfil FnPro = new FnProfil();
     FnPro.setVisible(true);
     this.setVisible(false);
    }//GEN-LAST:event_BtProfilActionPerformed

    private void BtHistoQuotActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtHistoQuotActionPerformed
     FnHistoQuot FnHistQuot = new FnHistoQuot();
     FnHistQuot.setVisible(true);
     this.setVisible(false);
    }//GEN-LAST:event_BtHistoQuotActionPerformed

    private void BtCreaObjActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtCreaObjActionPerformed
     FnCreaObj FnCrObj = new FnCreaObj();
     FnCrObj.setVisible(true);
     this.setVisible(false);
    }//GEN-LAST:event_BtCreaObjActionPerformed

    private void BtAperObjActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtAperObjActionPerformed
     FnApercu FnAper = new FnApercu();
     FnAper.setVisible(true);
     this.setVisible(false);
    }//GEN-LAST:event_BtAperObjActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FnConnected.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FnConnected.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FnConnected.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FnConnected.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FnConnected().setVisible(false);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BtAperObj;
    private javax.swing.JButton BtCreaObj;
    private javax.swing.JButton BtDeconnexion;
    private javax.swing.JButton BtHistoHebdo;
    private javax.swing.JButton BtHistoQuot;
    private javax.swing.JButton BtProfil;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    // End of variables declaration//GEN-END:variables
}
